[package]
name = "tar"
version = "0.1.0"
edition = "2024"

[dependencies]
cap-std = {version = "3.4.5", optional = true}
deku = "0.20.2"

[dev-dependencies]
tempfile = "3.23.0"

[features]
default = ["filesystem"]
filesystem = ["cap-std"]
